'use client';

import { useState, useRef } from 'react';
import { 
  Calculator, Settings, RefreshCw, Download,
  Plus, Minus, X as MultiplyIcon, Divide, 
  Hash, ArrowLeft, Layers, Loader2, FileDown, Check
} from 'lucide-react';
import Link from 'next/link';
import { motion, AnimatePresence } from 'framer-motion';
import { useTeacherLanguage } from '@/app/teacher/layout';
import toast from 'react-hot-toast';

// --- 1. TRANSLATION DICTIONARY ---
const WORKSHEET_TRANSLATIONS = {
  uz: {
    title: "Matematik Amallar", subtitle: "Qo'shish, ayirish, ko'paytirish va bo'lish",
    back: "Ortga", generate: "Yaratish", 
    download: "PDF Yuklab Olish", downloadAns: "Javoblar bilan PDF",
    operation: "Amallarni tanlang", ops: { add: "Qo'shish", sub: "Ayirish", mult: "Ko'paytirish", div: "Bo'lish" },
    digits: "Xonalar soni", topNum: "1-son (yoki Bo'linuvchi)", botNum: "2-son (yoki Bo'luvchi)",
    count: "Misollar soni", settings: "Sozlamalar",
    toggles: { noNeg: "Manfiy javoblar yo'q", rem: "Qoldiqli bo'lish", answers: "Javoblar varag'ini qo'shish" },
    preview: "Hujjat Ko'rinishi", ansTitle: "JAVOBLAR KALITI", name: "Ism", date: "Sana", score: "Baho",
    watermark: "Yaratilgan: testedify.uz"
  },
  en: {
    title: "Math Operations", subtitle: "Addition, Subtraction, Multiplication, Division",
    back: "Back", generate: "Generate", 
    download: "Download PDF", downloadAns: "PDF with Answers",
    operation: "Select Operations", ops: { add: "Addition", sub: "Subtraction", mult: "Multiplication", div: "Division" },
    digits: "Number of Digits", topNum: "Top Number (or Dividend)", botNum: "Bottom Number (or Divisor)",
    count: "Total Problems", settings: "Settings",
    toggles: { noNeg: "No negative answers", rem: "Allow remainders", answers: "Include Answer Key page" },
    preview: "Document Preview", ansTitle: "ANSWER KEY", name: "Name", date: "Date", score: "Score",
    watermark: "Generated by testedify.uz"
  },
  ru: {
    title: "Математические Операции", subtitle: "Сложение, вычитание, умножение и деление",
    back: "Назад", generate: "Сгенерировать", 
    download: "Скачать PDF", downloadAns: "PDF с ответами",
    operation: "Выберите операции", ops: { add: "Сложение", sub: "Вычитание", mult: "Умножение", div: "Деление" },
    digits: "Количество цифр", topNum: "1-е число (или Делимое)", botNum: "2-е число (или Делитель)",
    count: "Количество примеров", settings: "Настройки",
    toggles: { noNeg: "Без отрицательных ответов", rem: "Остаток при делении", answers: "Добавить лист с ответами" },
    preview: "Предпросмотр", ansTitle: "КЛЮЧИ ОТВЕТОВ", name: "Имя", date: "Дата", score: "Оценка",
    watermark: "Создано в testedify.uz"
  }
};

// --- TYPES ---
type Operation = '+' | '-' | '×' | '÷';
interface Problem { id: number; num1: number; num2: number; operator: Operation; answer: number; remainder?: number; }

const PROBLEMS_PER_PAGE = 24; // Optimal grid size for A4 (4 columns x 6 rows)
const DIVISION_PER_PAGE = 18; // Division takes more space (3 columns x 6 rows)

export default function MathOperationsGenerator() {
  const { lang } = useTeacherLanguage();
  const t = WORKSHEET_TRANSLATIONS[lang] || WORKSHEET_TRANSLATIONS['en'];

  // --- CONFIG STATE ---
  const [selectedOps, setSelectedOps] = useState<Operation[]>(['+']); // Array of selected operations
  const [topDigits, setTopDigits] = useState(2);
  const [botDigits, setBotDigits] = useState(2);
  const [problemCount, setProblemCount] = useState(24);
  
  // Toggles
  const [noNegatives, setNoNegatives] = useState(true);
  const [allowRemainders, setAllowRemainders] = useState(false);
  const [includeAnswers, setIncludeAnswers] = useState(true);

  // --- RESULTS STATE ---
  const [problems, setProblems] = useState<Problem[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isPdfLoading, setIsPdfLoading] = useState(false);
  
  const printRootRef = useRef<HTMLDivElement>(null);

  // --- MATH ENGINE ---
  const getRandom = (min: number, max: number) => Math.floor(Math.random() * (max - min + 1)) + min;
  const getMinMax = (digits: number) => ({ min: digits === 1 ? 1 : Math.pow(10, digits - 1), max: Math.pow(10, digits) - 1 });

  const toggleOperation = (op: Operation) => {
    setSelectedOps(prev => {
      if (prev.includes(op)) return prev.length > 1 ? prev.filter(o => o !== op) : prev;
      return [...prev, op];
    });
  };

  const generateProblems = () => {
    if (selectedOps.length === 0) return toast.error(t.operation);
    
    setIsGenerating(true);
    const newProblems: Problem[] = [];
    const topRange = getMinMax(topDigits);
    const botRange = getMinMax(botDigits);

    for (let i = 0; i < problemCount; i++) {
      // Pick a random operation from the selected ones
      const op = selectedOps[Math.floor(Math.random() * selectedOps.length)];
      
      let num1 = 0, num2 = 0, answer = 0, remainder = undefined;

      if (op === '÷') {
        const divisor = getRandom(botRange.min === 1 ? 2 : botRange.min, botRange.max); 
        const quotient = getRandom(topRange.min, topRange.max);
        
        num2 = divisor;
        answer = quotient;
        num1 = divisor * quotient; 

        if (allowRemainders) {
          remainder = getRandom(1, divisor - 1);
          if (remainder > 0) num1 += remainder;
        }
      } else {
        num1 = getRandom(topRange.min, topRange.max);
        num2 = getRandom(botRange.min, botRange.max);

        if (op === '-' && noNegatives && num2 > num1) {
          const temp = num1; num1 = num2; num2 = temp;
        }

        if (op === '+') answer = num1 + num2;
        if (op === '-') answer = num1 - num2;
        if (op === '×') answer = num1 * num2;
      }

      newProblems.push({ id: i + 1, num1, num2, operator: op, answer, remainder });
    }

    setTimeout(() => {
      setProblems(newProblems);
      setIsGenerating(false);
      window.scrollTo({ top: document.getElementById('preview-section')?.offsetTop || 0, behavior: 'smooth' });
    }, 400); 
  };

  // --- PDF GENERATOR ---
  const handleDownloadPdf = async (withAnswers: boolean) => {
    if (!printRootRef.current) return toast.error("Document not found!");
    setIsPdfLoading(true);
    
    const answerKeys = document.querySelectorAll('.answer-key-page');
    answerKeys.forEach((el: any) => el.style.display = withAnswers ? "block" : "none");

    const element = printRootRef.current;
    const originalTransform = element.style.transform;
    element.style.transform = "none"; // Remove scale for sharp render

    try {
      const html2pdf = (await import("html2pdf.js")).default;
      const opt = {
      margin:       0, 
      filename:     `Math_Worksheet_${Date.now()}.pdf`,
      image:        { type: 'jpeg' as const, quality: 1 }, // <-- Add "as const" here
      html2canvas:  { scale: 2, useCORS: true, logging: false },
      jsPDF:        { unit: 'mm', format: 'a4', orientation: 'portrait' as const } // Might as well add it here too just in case!
    };

      await html2pdf().set(opt).from(element).save();
      toast.success("PDF Downloaded!");

    } catch (error) {
      console.error(error);
      toast.error("Failed to create PDF.");
    } finally {
      element.style.transform = originalTransform;
      answerKeys.forEach((el: any) => el.style.display = "block"); // Restore visibility for preview
      setIsPdfLoading(false);
    }
  };

  // --- RENDER HELPERS ---
  const ProblemCard = ({ p, isAnswerKey }: { p: Problem, isAnswerKey: boolean }) => {
    // European Division Layout
    if (p.operator === '÷') {
      return (
        <div className="relative p-2 md:p-4 flex flex-col items-center justify-start min-h-[160px] md:min-h-[200px]">
          <span className="absolute top-0 left-0 font-black text-slate-400 text-[10px] md:text-[12px]">{p.id})</span>
          <div className="flex items-start w-full justify-center mt-3 md:mt-4 text-lg md:text-xl font-mono tracking-widest text-slate-900">
            <div className="pr-2">{p.num1}</div>
            <div className="border-l-2 border-slate-900 pl-2 flex flex-col items-start min-w-[2.5rem] md:min-w-[3rem]">
               <div className="pb-1">{p.num2}</div>
               <div className="border-t-2 border-slate-900 w-full pt-1 text-indigo-600 font-bold h-8 flex items-center justify-center">
                 {isAnswerKey ? <span>{p.answer} {p.remainder ? <span className="text-[10px] md:text-sm ml-1">r{p.remainder}</span> : ''}</span> : ''}
               </div>
            </div>
          </div>
        </div>
      );
    }

    // Vertical Stack Layout (+, -, ×)
    return (
      <div className={`relative p-2 md:p-4 flex flex-col items-center justify-start min-h-[120px] md:min-h-[140px]`}>
        <span className="absolute top-0 left-0 font-black text-slate-400 text-[10px] md:text-[12px]">{p.id})</span>
        <div className="flex flex-col items-end text-lg md:text-xl font-mono tracking-widest text-slate-900 mt-3 md:mt-4">
          <div>{p.num1}</div>
          <div className="flex items-center w-full justify-between gap-4 md:gap-6 border-b-2 border-slate-900 pb-1">
            <span>{p.operator}</span>
            <span>{p.num2}</span>
          </div>
          {isAnswerKey ? (
             <div className="text-indigo-600 font-bold pt-1 text-center w-full">{p.answer}</div>
          ) : (
             <div className="h-6 md:h-8 w-full"></div> 
          )}
        </div>
      </div>
    );
  };

  // Helper to chunk problems into A4 pages
  const chunkArray = (arr: any[], size: number) => {
    return Array.from({ length: Math.ceil(arr.length / size) }, (v, i) => arr.slice(i * size, i * size + size));
  };

  const perPage = selectedOps.includes('÷') && selectedOps.length === 1 ? DIVISION_PER_PAGE : PROBLEMS_PER_PAGE;
  const problemPages = chunkArray(problems, perPage);

  return (
    <div className="min-h-[100dvh] bg-[#F8FAFC] font-sans pb-[calc(2rem+env(safe-area-inset-bottom))]">
      
      {/* --- TOP HEADER --- */}
      <div className="bg-white/90 backdrop-blur-xl border-b border-slate-200 sticky top-0 z-30 shadow-sm">
        <div className="max-w-5xl mx-auto px-4 py-3 md:py-4 flex items-center gap-3">
          <Link href="/teacher/create" className="p-2 -ml-2 text-slate-400 hover:text-slate-900 hover:bg-slate-100 rounded-xl transition-colors active:scale-95">
            <ArrowLeft size={20} strokeWidth={2.5} />
          </Link>
          <div className="min-w-0">
            <h1 className="text-[16px] md:text-[18px] font-black text-slate-900 tracking-tight flex items-center gap-2 truncate">
              <Calculator size={18} className="text-indigo-600 shrink-0" strokeWidth={2.5}/> {t.title}
            </h1>
          </div>
        </div>
      </div>

      <div className="max-w-5xl mx-auto px-4 mt-6 md:mt-8">
        
        {/* --- CONFIGURATION PANEL --- */}
        <div className="bg-white rounded-[1.5rem] md:rounded-[2rem] border border-slate-200/80 shadow-sm p-4 md:p-6 mb-6 md:mb-8">
          
          {/* 1. Operation Multi-Select Cards */}
          <div className="mb-6 md:mb-8">
            <h2 className="text-[10px] md:text-[11px] font-black text-slate-400 uppercase tracking-widest mb-3 md:mb-4 flex items-center gap-1.5 ml-1">
              <Layers size={14} /> 1. {t.operation}
            </h2>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
               {[
                 { id: '+', icon: Plus, label: t.ops.add, color: 'emerald' },
                 { id: '-', icon: Minus, label: t.ops.sub, color: 'amber' },
                 { id: '×', icon: MultiplyIcon, label: t.ops.mult, color: 'blue' },
                 { id: '÷', icon: Divide, label: t.ops.div, color: 'purple' }
               ].map(op => {
                 const isActive = selectedOps.includes(op.id as Operation);
                 return (
                   <button 
                     key={op.id} 
                     onClick={() => toggleOperation(op.id as Operation)}
                     className={`relative flex flex-col items-center justify-center gap-2 md:gap-3 p-3 md:p-5 rounded-2xl border-2 transition-all duration-200 active:scale-[0.98] ${
                       isActive 
                         ? `border-${op.color}-500 bg-${op.color}-50 shadow-sm ring-2 ring-${op.color}-500/20` 
                         : 'border-slate-200 bg-white hover:border-slate-300'
                     }`}
                   >
                     {isActive && <div className={`absolute top-2 right-2 w-4 h-4 bg-${op.color}-500 rounded-full flex items-center justify-center`}><Check size={10} className="text-white" strokeWidth={4}/></div>}
                     <div className={`w-10 h-10 md:w-12 md:h-12 rounded-full flex items-center justify-center transition-colors duration-200 ${isActive ? `bg-${op.color}-500 text-white shadow-md` : `bg-slate-50 text-slate-400 border border-slate-100`}`}>
                       <op.icon size={20} className="md:w-6 md:h-6" strokeWidth={isActive ? 3 : 2.5} />
                     </div>
                     <span className={`text-[12px] md:text-[14px] font-black tracking-wide ${isActive ? `text-${op.color}-700` : 'text-slate-500'}`}>
                       {op.label}
                     </span>
                   </button>
                 );
               })}
            </div>
          </div>

          <div className="grid md:grid-cols-2 gap-4 md:gap-6">
             
             {/* 2. Digits & Count */}
             <div className="bg-slate-50/50 p-4 md:p-5 rounded-[1.2rem] border border-slate-100 flex flex-col justify-between space-y-4">
                <h2 className="text-[10px] md:text-[11px] font-black text-slate-400 uppercase tracking-widest flex items-center gap-1.5">
                  <Hash size={14} /> 2. {t.digits}
                </h2>
                
                {/* Top Digits */}
                <div>
                  <p className="text-[11px] md:text-[12px] font-black text-slate-600 mb-2 pl-1">{t.topNum}</p>
                  <div className="flex gap-1.5 md:gap-2">
                    {[1, 2, 3, 4, 5, 6].map(n => (
                      <button key={`top-${n}`} onClick={() => setTopDigits(n)} className={`flex-1 py-2 md:py-2.5 rounded-xl text-[12px] md:text-[14px] font-black border transition-all active:scale-95 ${topDigits === n ? 'bg-indigo-600 text-white border-indigo-600 shadow-md shadow-indigo-600/20' : 'bg-white text-slate-500 border-slate-200 hover:border-indigo-300'}`}>{n}</button>
                    ))}
                  </div>
                </div>
                
                {/* Bottom Digits */}
                <div>
                  <p className="text-[11px] md:text-[12px] font-black text-slate-600 mb-2 pl-1">{t.botNum}</p>
                  <div className="flex gap-1.5 md:gap-2">
                    {[1, 2, 3, 4, 5, 6].map(n => (
                      <button key={`bot-${n}`} onClick={() => setBotDigits(n)} className={`flex-1 py-2 md:py-2.5 rounded-xl text-[12px] md:text-[14px] font-black border transition-all active:scale-95 ${botDigits === n ? 'bg-indigo-600 text-white border-indigo-600 shadow-md shadow-indigo-600/20' : 'bg-white text-slate-500 border-slate-200 hover:border-indigo-300'}`}>{n}</button>
                    ))}
                  </div>
                </div>

                {/* Problem Count Slider */}
                <div className="pt-2 border-t border-slate-200/60">
                  <div className="flex justify-between items-center mb-3">
                    <p className="text-[11px] md:text-[12px] font-black text-slate-600 pl-1">{t.count}</p>
                    <span className="bg-indigo-100 text-indigo-700 font-black px-2.5 py-1 rounded-lg text-[10px] md:text-[11px] uppercase tracking-widest">{problemCount} ta</span>
                  </div>
                  <input type="range" min="12" max="60" step="4" value={problemCount} onChange={(e) => setProblemCount(Number(e.target.value))} className="w-full accent-indigo-600 cursor-pointer h-2 bg-slate-200 rounded-lg appearance-none shadow-inner"/>
                </div>
             </div>

             {/* 3. Settings & Generate */}
             <div className="flex flex-col">
                <div className="bg-slate-50/50 p-4 md:p-5 rounded-[1.2rem] border border-slate-100 flex-1 flex flex-col justify-between">
                  <h2 className="text-[10px] md:text-[11px] font-black text-slate-400 uppercase tracking-widest flex items-center gap-1.5 mb-4">
                    <Settings size={14} /> 3. {t.settings}
                  </h2>
                  
                  <div className="space-y-4 mb-6">
                    {selectedOps.includes('-') && (
                      <label className="flex items-center justify-between cursor-pointer group bg-white px-4 py-3 rounded-xl border border-slate-200/80 shadow-sm active:scale-[0.98] transition-all">
                          <span className="text-[12px] md:text-[13px] font-black text-slate-700">{t.toggles.noNeg}</span>
                          <div className={`w-10 h-6 rounded-full p-1 transition-colors ${noNegatives ? 'bg-indigo-500' : 'bg-slate-200'}`}>
                            <div className={`w-4 h-4 bg-white rounded-full shadow-sm transition-transform ${noNegatives ? 'translate-x-4' : 'translate-x-0'}`}/>
                          </div>
                          <input type="checkbox" className="hidden" checked={noNegatives} onChange={() => setNoNegatives(!noNegatives)}/>
                      </label>
                    )}

                    {selectedOps.includes('÷') && (
                      <label className="flex items-center justify-between cursor-pointer group bg-white px-4 py-3 rounded-xl border border-slate-200/80 shadow-sm active:scale-[0.98] transition-all">
                          <span className="text-[12px] md:text-[13px] font-black text-slate-700">{t.toggles.rem}</span>
                          <div className={`w-10 h-6 rounded-full p-1 transition-colors ${allowRemainders ? 'bg-indigo-500' : 'bg-slate-200'}`}>
                            <div className={`w-4 h-4 bg-white rounded-full shadow-sm transition-transform ${allowRemainders ? 'translate-x-4' : 'translate-x-0'}`}/>
                          </div>
                          <input type="checkbox" className="hidden" checked={allowRemainders} onChange={() => setAllowRemainders(!allowRemainders)}/>
                      </label>
                    )}

                    <label className="flex items-center justify-between cursor-pointer group bg-white px-4 py-3 rounded-xl border border-slate-200/80 shadow-sm active:scale-[0.98] transition-all">
                        <span className="text-[12px] md:text-[13px] font-black text-slate-700">{t.toggles.answers}</span>
                        <div className={`w-10 h-6 rounded-full p-1 transition-colors ${includeAnswers ? 'bg-indigo-500' : 'bg-slate-200'}`}>
                          <div className={`w-4 h-4 bg-white rounded-full shadow-sm transition-transform ${includeAnswers ? 'translate-x-4' : 'translate-x-0'}`}/>
                        </div>
                        <input type="checkbox" className="hidden" checked={includeAnswers} onChange={() => setIncludeAnswers(!includeAnswers)}/>
                    </label>
                  </div>

                  {/* Generate Button */}
                  <button 
                    onClick={generateProblems} 
                    className="w-full py-3.5 md:py-4 bg-slate-900 hover:bg-black text-white font-black rounded-xl shadow-lg shadow-slate-900/20 flex items-center justify-center gap-2 transition-all active:scale-[0.98] text-[13px] md:text-[14px] mt-auto"
                  >
                    <RefreshCw size={18} className={isGenerating ? "animate-spin" : ""} strokeWidth={2.5}/> 
                    {isGenerating ? "Yaratilmoqda..." : t.generate}
                  </button>

                </div>
             </div>

          </div>
        </div>

        {/* --- PREVIEW & DOWNLOAD SECTION --- */}
        <div id="preview-section" className="scroll-mt-24">
          <AnimatePresence mode="wait">
            {problems.length > 0 && (
              <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="space-y-4 md:space-y-6">
                
                {/* Action Bar */}
                <div className="flex flex-col sm:flex-row justify-between items-center bg-white p-3 md:p-4 rounded-[1.2rem] md:rounded-[1.5rem] border border-slate-200 shadow-sm gap-3">
                   <h3 className="font-black text-slate-800 text-[13px] md:text-[15px] flex items-center gap-2 px-2"><FileDown size={18} className="text-indigo-500"/> {t.preview}</h3>
                   <div className="flex flex-col sm:flex-row gap-2 md:gap-3 w-full sm:w-auto">
                     <button 
                       onClick={() => handleDownloadPdf(false)} disabled={isPdfLoading}
                       className="w-full sm:w-auto px-5 md:px-6 py-3 md:py-2.5 bg-slate-50 border border-slate-200/80 text-slate-700 hover:bg-slate-100 hover:text-slate-900 font-bold rounded-xl transition-all flex items-center justify-center gap-2 active:scale-95 disabled:opacity-50 text-[12px] md:text-[13px]"
                     >
                       {isPdfLoading ? <Loader2 size={16} className="animate-spin"/> : <Download size={16} strokeWidth={2.5}/>} {t.download}
                     </button>
                     {includeAnswers && (
                       <button 
                         onClick={() => handleDownloadPdf(true)} disabled={isPdfLoading}
                         className="w-full sm:w-auto px-5 md:px-6 py-3 md:py-2.5 bg-indigo-50 border border-indigo-100 text-indigo-700 hover:bg-indigo-100 hover:border-indigo-200 font-bold rounded-xl transition-all flex items-center justify-center gap-2 active:scale-95 disabled:opacity-50 text-[12px] md:text-[13px]"
                       >
                         {isPdfLoading ? <Loader2 size={16} className="animate-spin"/> : <Download size={16} strokeWidth={2.5}/>} {t.downloadAns}
                       </button>
                     )}
                   </div>
                </div>

                {/* THE A4 CANVAS WRAPPER (Scaled for preview) */}
                <div className="bg-slate-200/50 p-2 md:p-6 rounded-[1.5rem] md:rounded-[2rem] overflow-x-auto flex flex-col items-center custom-scrollbar border border-slate-200 shadow-inner">
                  
                  {/* REAL A4 CONTAINER */}
                  <div 
                    ref={printRootRef}
                    className="origin-top flex flex-col gap-8"
                    style={{ transform: 'scale(0.85)', transformOrigin: 'top center', marginBottom: '-15%' }}
                  >
                    
                    {/* --- STUDENT WORKSHEET PAGES --- */}
                    {problemPages.map((pageProblems, pageIndex) => (
                      <div 
                        key={`student-page-${pageIndex}`}
                        className="bg-white shadow-2xl relative flex flex-col justify-between"
                        style={{ width: '210mm', minHeight: '297mm', padding: '15mm', boxSizing: 'border-box', pageBreakAfter: 'always' }}
                      >
                        <div>
                          {/* Header (Only on first page, or minimal on subsequent) */}
                          <div className="flex justify-between items-end border-b-[3px] border-slate-900 pb-4 mb-8">
                            <h1 className="text-[26px] font-black uppercase text-black tracking-tight leading-none">{t.title}</h1>
                            {pageIndex === 0 && (
                              <div className="flex flex-col gap-3.5 text-[14px] w-64 shrink-0">
                                 <div className="flex items-end gap-2"><span className="font-bold uppercase tracking-widest">{t.name}:</span><div className="flex-1 border-b-2 border-slate-400"></div></div>
                                 <div className="flex items-end gap-2"><span className="font-bold uppercase tracking-widest">{t.date}:</span><div className="flex-1 border-b-2 border-slate-400"></div><span className="font-bold uppercase tracking-widest ml-2">{t.score}:</span><div className="w-12 border-b-2 border-slate-400"></div></div>
                              </div>
                            )}
                            {pageIndex > 0 && <span className="font-black text-slate-400">Page {pageIndex + 1}</span>}
                          </div>

                          {/* Grid */}
                          <div className={`grid ${perPage === DIVISION_PER_PAGE ? 'grid-cols-3 gap-y-10 gap-x-8' : 'grid-cols-4 gap-y-8 gap-x-6'}`}>
                             {pageProblems.map(p => <ProblemCard key={`q-${p.id}`} p={p} isAnswerKey={false} />)}
                          </div>
                        </div>

                        {/* Footer Watermark */}
                        <div className="w-full text-center border-t-2 border-slate-100 pt-3 mt-auto">
                          <p className="text-[10px] font-black text-slate-300 uppercase tracking-widest">{t.watermark}</p>
                        </div>
                      </div>
                    ))}

                    {/* --- ANSWER KEY PAGES --- */}
                    {includeAnswers && problemPages.map((pageProblems, pageIndex) => (
                      <div 
                        key={`answer-page-${pageIndex}`}
                        className="bg-white shadow-2xl relative answer-key-page flex flex-col justify-between"
                        style={{ width: '210mm', minHeight: '297mm', padding: '15mm', boxSizing: 'border-box', pageBreakAfter: 'always' }}
                      >
                        <div>
                          <div className="border-b-[3px] border-indigo-500 pb-4 mb-8 flex justify-between items-end">
                            <h1 className="text-[26px] font-black uppercase text-indigo-600 tracking-tight leading-none">{t.ansTitle}</h1>
                            <span className="font-black text-indigo-300">Page {pageIndex + 1}</span>
                          </div>

                          <div className={`grid ${perPage === DIVISION_PER_PAGE ? 'grid-cols-3 gap-y-10 gap-x-8' : 'grid-cols-4 gap-y-8 gap-x-6'}`}>
                             {pageProblems.map(p => <ProblemCard key={`a-${p.id}`} p={p} isAnswerKey={true} />)}
                          </div>
                        </div>

                        <div className="w-full text-center border-t-2 border-slate-100 pt-3 mt-auto">
                          <p className="text-[10px] font-black text-slate-300 uppercase tracking-widest">{t.watermark}</p>
                        </div>
                      </div>
                    ))}

                  </div>
                </div>
                
              </motion.div>
            )}
          </AnimatePresence>
        </div>

      </div>
    </div>
  );
}